"""Module extensions for tools_gcloud (bzlmod)."""

load("//gcloud/private:repo.bzl", "gcloud_toolchains")

_OS_TO_CONSTRAINT = {
    "darwin": "@platforms//os:macos",
    "linux": "@platforms//os:linux",
}

_ARCH_TO_CONSTRAINT = {
    "amd64": "@platforms//cpu:x86_64",
    "arm64": "@platforms//cpu:aarch64",
}

_PLATFORMS = ["darwin_arm64", "darwin_amd64", "linux_arm64", "linux_amd64"]

_TOOLCHAIN_BUILD_HEADER = """# Generated by tools_gcloud

load("@tools_gcloud//gcloud/private:toolchain.bzl", "gcloud_toolchain")

package(default_visibility = ["//visibility:public"])
"""

_TOOLCHAIN_BUILD_TEMPLATE = """
gcloud_toolchain(
    name = "{platform}_impl",
    gcloud = "@gcloud_{platform}//:gcloud",
)

toolchain(
    name = "{platform}",
    exec_compatible_with = [
        {exec_constraints},
    ],
    toolchain = ":{platform}_impl",
    toolchain_type = "@tools_gcloud//gcloud:toolchain_type",
)

toolchain(
    name = "{platform}_runtime",
    target_compatible_with = [
        {exec_constraints},
    ],
    toolchain = ":{platform}_impl",
    toolchain_type = "@tools_gcloud//gcloud:runtime_toolchain_type",
)
"""

def _gcloud_toolchains_repo_impl(repository_ctx):
    """Creates a repository with toolchain definitions for all platforms."""
    lines = [_TOOLCHAIN_BUILD_HEADER]

    for platform in _PLATFORMS:
        os_name, arch = platform.split("_")
        exec_constraints = [
            _OS_TO_CONSTRAINT[os_name],
            _ARCH_TO_CONSTRAINT[arch],
        ]
        exec_constraints_str = ",\n        ".join(['"{}"'.format(c) for c in exec_constraints])

        lines.append(_TOOLCHAIN_BUILD_TEMPLATE.format(
            platform = platform,
            exec_constraints = exec_constraints_str,
        ))

    repository_ctx.file("BUILD.bazel", content = "\n".join(lines))

_gcloud_toolchains_repo = repository_rule(
    implementation = _gcloud_toolchains_repo_impl,
)

def _gcloud_impl(module_ctx):
    """Implementation of the gcloud module extension."""

    # Check for mismatched versions
    root_download = None
    versions = {}  # version -> download tag
    for mod in module_ctx.modules:
        for download in mod.tags.download:
            if mod.is_root and not root_download:
                root_download = download
            if download.version and download.version not in versions:
                versions[download.version] = download
    if len(versions) > 1:
        fail("Conflicting gcloud CLI versions requested: {}".format(", ".join(versions.keys())))

    # Use specified version if any, otherwise use root module settings
    download = versions.values()[0] if versions else root_download
    version = download.version if download else ""
    sha256 = download.sha256 if download else {}
    use_latest = download.use_latest if download else False

    # Download the gcloud CLI for each platform
    for platform in _PLATFORMS:
        gcloud_toolchains(
            name = "gcloud_" + platform,
            version = version,
            platform = platform,
            sha256 = sha256.get(platform, ""),
            use_latest = use_latest,
        )

    # Create the toolchains repository
    _gcloud_toolchains_repo(name = "gcloud_toolchains")

_download = tag_class(
    attrs = {
        "version": attr.string(
            doc = "Version to download. If empty, uses default version.",
        ),
        "sha256": attr.string_dict(
            doc = "SHA256 hashes per platform (e.g., {'darwin_arm64': 'abc...', 'linux_amd64': 'def...'}).",
        ),
        "use_latest": attr.bool(
            default = False,
            doc = "If true, fetches the latest version instead of the default.",
        ),
    },
)

gcloud = module_extension(
    implementation = _gcloud_impl,
    tag_classes = {
        "download": _download,
    },
)
